import type {
  User,
  TwoFactorProfile,
  ReportApi,
  ReportsResponse,
  DashboardApi,
  ReportRecordApi,
  RecordsResponse,
  NotificationsApi,
} from '@/types/api';

export const mockUser: User = {
  id: 'mock-user-1',
  name: 'John Doe',
  email: 'john.doe@example.com',
  sharedAggregatePostboxAddress: 'xxxxxxxxxxxxxx@reports.example.com',
};

export const mockTwoFactorProfile: TwoFactorProfile = {
  twoFactorMethod: null,
  twoFactorAppEnabled: false,
  twoFactorAppSecret: 'MOCK2FASECRET',
  twoFactorAppOtpAuthUri: 'otpauth://totp/DMARCo:john.doe@example.com?secret=MOCK2FASECRET&issuer=DMARCo',
  twoFactorAppQrContent: null,
};

export const mockNotificationSettings: NotificationsApi = {
  unusualNewLoginNotificationEnabled: true,
  weeklyOverviewNotificationEnabled: true,
};

export const mockDashboard: DashboardApi = {
  reportCount: 156,
  reportTrend: 12.5,
  messageCount: 48720,
  messageTrend: 8.3,
  passRate: 0.942, // 0-1 float representing 94.2%
  passTrend: 2.1,
  threatsBlockedCount: 2810,
  threatsBlockedTrend: -5.2,
  messageCountByDate: {
    '2024-06-14': 5420,
    '2024-06-15': 6890,
    '2024-06-16': 4230,
    '2024-06-17': 8150,
    '2024-06-18': 5890,
    '2024-06-19': 7340,
    '2024-06-20': 8800,
  },
  threatCountByDate: {
    '2024-06-14': 320,
    '2024-06-15': 410,
    '2024-06-16': 275,
    '2024-06-17': 505,
    '2024-06-18': 360,
    '2024-06-19': 470,
    '2024-06-20': 520,
  },
  compliance: {
    dmarc: 0.80,
    dkim: 0.875,
    spf: 0.894,
  },
  complianceTrend: {
    dmarc: 5.2,
    dkim: 3.1,
    spf: -1.8,
  },
  newDomainCount: 7,
  newDomainTrend: 75,
  newDomains: [
    'example.com',
    'example.net',
    'mail.example',
  ],
  topOffenders: [
    {
      sourceIp: '192.0.2.10',
      count: 2810,
      sourceIpInfo: {
        orgName: 'Example Hosting GmbH',
        orgCountry: 'DE',
        orgAbuseEmail: 'abuse@hosting.example',
        orgTechEmail: 'noc@hosting.example',
      },
    },
    {
      sourceIp: '192.0.2.44',
      count: 1245,
      sourceIpInfo: {
        orgName: 'Northern Transit Networks',
        orgCountry: 'SE',
        orgAbuseEmail: null,
        orgTechEmail: 'tech@transit.example',
      },
    },
    {
      sourceIp: '203.0.113.42',
      count: 892,
      sourceIpInfo: {
        orgName: null,
        orgCountry: 'US',
        orgAbuseEmail: 'abuse@provider.example',
        orgTechEmail: null,
      },
    },
    {
      sourceIp: '198.51.100.23',
      count: 456,
      sourceIpInfo: {
        orgName: 'Cloud Relay Services',
        orgCountry: null,
        orgAbuseEmail: null,
        orgTechEmail: null,
      },
    },
    {
      sourceIp: '192.0.2.91',
      count: 123,
      sourceIpInfo: {
        orgName: null,
        orgCountry: null,
        orgAbuseEmail: null,
        orgTechEmail: null,
      },
    },
  ],
  topSenders: [
    {
      sourceIp: '198.51.100.41',
      count: 9450,
      sourceIpInfo: {
        orgName: 'Example Mail Provider',
        orgCountry: 'US',
        orgAbuseEmail: 'network-abuse@provider.example',
        orgTechEmail: 'noc@provider.example',
      },
    },
    {
      sourceIp: '198.51.100.12',
      count: 6120,
      sourceIpInfo: {
        orgName: 'Example Cloud Services',
        orgCountry: 'US',
        orgAbuseEmail: null,
        orgTechEmail: 'hostmaster@cloud.example',
      },
    },
    {
      sourceIp: '198.51.100.120',
      count: 3275,
      sourceIpInfo: {
        orgName: 'Example Secure Mail AG',
        orgCountry: 'CH',
        orgAbuseEmail: 'abuse@securemail.example',
        orgTechEmail: null,
      },
    },
    {
      sourceIp: null,
      count: 1120,
      sourceIpInfo: {
        orgName: null,
        orgCountry: null,
        orgAbuseEmail: null,
        orgTechEmail: null,
      },
    },
  ],
  topReportingOrganizations: [
    { reportingOrganization: 'Google Inc.', count: 42 },
    { reportingOrganization: 'Microsoft Corporation', count: 31 },
    { reportingOrganization: 'Yahoo! Inc.', count: 18 },
    { reportingOrganization: 'Proton AG', count: 11 },
    { reportingOrganization: null, count: 3 },
  ],
  sourceCountryDistribution: [
    { country: 'US', count: 73 },
    { country: 'DE', count: 31 },
    { country: 'CH', count: 14 },
    { country: '', count: 8 },
    { country: null, count: 4 },
  ],
};

export const mockReportsList: ReportApi[] = [
  {
    id: 'report-1',
    domainId: '1',
    reportId: 'google.com!example.com!1718323200!1718409600',
    fromAddress: 'noreply-dmarc-support@google.com',
    reportingOrganization: 'Google Inc.',
    reportingOrganizationEmail: 'noreply-dmarc-support@google.com',
    reportingOrganizationExtraContact: 'https://support.google.com/a/answer/2466580',
    domain: 'example.com',
    beginDate: { date: '2024-06-14 00:00:00.000000', timezone_type: 3, timezone: 'UTC' },
    endDate: { date: '2024-06-15 00:00:00.000000', timezone_type: 3, timezone: 'UTC' },
    sumCount: 4520,
    dmarcCompliance: 0.95,
    spfCompliance: 0.95,
    dkimCompliance: 0.98,
    adkimPolicy: 'r',
    aspfPolicy: 'r',
    pPolicy: 'reject',
    spPolicy: 'reject',
    pctPolicy: 100,
    npPolicy: null,
    lastChecked: null,
    lastError: null,
    isVerified: true,
  },
  {
    id: 'report-2',
    domainId: '1',
    reportId: 'microsoft.com!example.com!1718323200!1718409600',
    fromAddress: 'mailer-daemon@microsoft.com',
    reportingOrganization: 'Microsoft Corporation',
    reportingOrganizationEmail: 'dmarcreport@microsoft.com',
    reportingOrganizationExtraContact: null,
    domain: 'example.com',
    beginDate: { date: '2024-06-14 00:00:00.000000', timezone_type: 3, timezone: 'UTC' },
    endDate: { date: '2024-06-15 00:00:00.000000', timezone_type: 3, timezone: 'UTC' },
    sumCount: 2180,
    dmarcCompliance: 0.95,
    spfCompliance: 0.88,
    dkimCompliance: 0.92,
    adkimPolicy: 'r',
    aspfPolicy: 'r',
    pPolicy: 'reject',
    spPolicy: 'reject',
    pctPolicy: 100,
    npPolicy: null,
    lastChecked: null,
    lastError: null,
    isVerified: true,
  },
  {
    id: 'report-3',
    domainId: '1',
    reportId: 'yahoo.com!example.com!1718409600!1718496000',
    fromAddress: 'dmarc-report@yahoo.com',
    reportingOrganization: 'Yahoo! Inc.',
    reportingOrganizationEmail: 'dmarc-report@yahoo.com',
    reportingOrganizationExtraContact: null,
    domain: 'example.com',
    beginDate: { date: '2024-06-15 00:00:00.000000', timezone_type: 3, timezone: 'UTC' },
    endDate: { date: '2024-06-16 00:00:00.000000', timezone_type: 3, timezone: 'UTC' },
    sumCount: 890,
    dmarcCompliance: 0.95,
    spfCompliance: 0.45,
    dkimCompliance: 0.72,
    adkimPolicy: 'r',
    aspfPolicy: 'r',
    pPolicy: 'quarantine',
    spPolicy: 'quarantine',
    pctPolicy: 100,
    npPolicy: null,
    lastChecked: null,
    lastError: null,
    isVerified: false,
  },
  {
    id: 'report-4',
    domainId: '2',
    reportId: 'google.com!example.net!1718409600!1718496000',
    fromAddress: 'noreply-dmarc-support@google.com',
    reportingOrganization: 'Google Inc.',
    reportingOrganizationEmail: 'noreply-dmarc-support@google.com',
    reportingOrganizationExtraContact: 'https://support.google.com/a/answer/2466580',
    domain: 'example.net',
    beginDate: { date: '2024-06-15 00:00:00.000000', timezone_type: 3, timezone: 'UTC' },
    endDate: { date: '2024-06-16 00:00:00.000000', timezone_type: 3, timezone: 'UTC' },
    sumCount: 6230,
    dmarcCompliance: 0.95,
    spfCompliance: 0.99,
    dkimCompliance: 1.0,
    adkimPolicy: 'r',
    aspfPolicy: 'r',
    pPolicy: 'reject',
    spPolicy: 'reject',
    pctPolicy: 100,
    npPolicy: null,
    lastChecked: null,
    lastError: null,
    isVerified: true,
  },
  {
    id: 'report-5',
    domainId: '1',
    reportId: 'protonmail.com!example.com!1718496000!1718582400',
    fromAddress: 'no-reply@protonmail.com',
    reportingOrganization: 'Proton AG',
    reportingOrganizationEmail: 'dmarc-reports@protonmail.com',
    reportingOrganizationExtraContact: null,
    domain: 'example.com',
    beginDate: { date: '2024-06-16 00:00:00.000000', timezone_type: 3, timezone: 'UTC' },
    endDate: { date: '2024-06-17 00:00:00.000000', timezone_type: 3, timezone: 'UTC' },
    sumCount: 450,
    dmarcCompliance: 0.95,
    spfCompliance: 0.35,
    dkimCompliance: 0.40,
    adkimPolicy: 'r',
    aspfPolicy: 'r',
    pPolicy: 'reject',
    spPolicy: 'reject',
    pctPolicy: 100,
    npPolicy: null,
    lastChecked: null,
    lastError: null,
    isVerified: null,
  },
];

export const mockRecords: ReportRecordApi[] = [
  {
    id: 'record-1',
    reportId: 'report-1',
    sourceIp: '198.51.100.41',
    sourceIpInfo: {
      orgName: 'Example Mail Provider',
      orgCountry: 'US',
      orgAbuseEmail: 'network-abuse@provider.example',
      orgTechEmail: 'noc@provider.example',
    },
    count: 3250,
    disposition: 'none',
    dkimAlign: 'pass',
    spfAlign: 'pass',
    dkimAuth: 'pass',
    dkimDomain: 'example.com',
    dkimSelector: 'google',
    spfAuth: 'pass',
    spfDomain: 'example.com',
  },
  {
    id: 'record-2',
    reportId: 'report-1',
    sourceIp: '198.51.100.42',
    sourceIpInfo: {
      orgName: 'Example Mail Provider',
      orgCountry: 'US',
      orgAbuseEmail: 'network-abuse@provider.example',
      orgTechEmail: 'noc@provider.example',
    },
    count: 890,
    disposition: 'none',
    dkimAlign: 'pass',
    spfAlign: 'pass',
    dkimAuth: 'pass',
    dkimDomain: 'example.com',
    dkimSelector: 'google',
    spfAuth: 'pass',
    spfDomain: 'example.com',
  },
  {
    id: 'record-3',
    reportId: 'report-1',
    sourceIp: '192.0.2.10',
    sourceIpInfo: {
      orgName: 'Unidentified Network',
      orgCountry: null,
      orgAbuseEmail: null,
      orgTechEmail: null,
    },
    count: 180,
    disposition: 'reject',
    dkimAlign: 'fail',
    spfAlign: 'fail',
    dkimAuth: 'fail',
    dkimDomain: 'spoofed-sender.example',
    dkimSelector: null,
    spfAuth: 'fail',
    spfDomain: 'spoofed-sender.example',
  },
  {
    id: 'record-4',
    reportId: 'report-1',
    sourceIp: '198.51.100.50',
    sourceIpInfo: {
      orgName: 'Example Mail Provider',
      orgCountry: 'US',
      orgAbuseEmail: 'network-abuse@provider.example',
      orgTechEmail: 'noc@provider.example',
    },
    count: 200,
    disposition: 'none',
    dkimAlign: 'pass',
    spfAlign: 'fail',
    dkimAuth: 'pass',
    dkimDomain: 'example.com',
    dkimSelector: 'selector1',
    spfAuth: 'fail',
    spfDomain: 'other.example',
  },
];

export const mockReportsResponse = (page = 1, pageSize = 10): ReportsResponse => {
  const start = (page - 1) * pageSize;
  const end = start + pageSize;
  const items = mockReportsList.slice(start, end);
  
  return {
    items,
    meta: {
      totalCount: mockReportsList.length,
      pageCount: Math.ceil(mockReportsList.length / pageSize),
      filterableFields: ['domain', 'reportingOrganization'],
      sortableFields: ['domain', 'beginDate', 'endDate', 'sumCount'],
    },
  };
};

export const getMockReportById = (id: string): ReportApi => {
  const report = mockReportsList.find(r => r.id === id);
  return report || mockReportsList[0];
};

export const mockRecordsResponse = (reportId: string): RecordsResponse => {
  const records = mockRecords.filter(r => r.reportId === reportId || reportId === 'report-1');
  return {
    items: records.length > 0 ? records : mockRecords,
    meta: {
      totalCount: records.length || mockRecords.length,
      pageCount: 1,
      filterableFields: ['sourceIp', 'disposition'],
      sortableFields: ['sourceIp', 'count'],
    },
  };
};
